---

- name: Disabling SELinux
  selinux:
    state: disabled
  become: true

- name: Install Java 1.8
  yum: name=java state=latest

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://mirrors.ibiblio.org/apache/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz dest=/opt/apache-tomcat-8.5.32.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.32.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.32

- name: Symlink install directory
  file: src=/opt/apache-tomcat-8.5.32 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes


- name: Start Tomcat
  shell: sh /usr/share/tomcat/bin/startup.sh

